# Generated by Django 2.2.28 on 2024-01-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
